//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Calories { get; set; }
        public Nullable<int> Protein { get; set; }
        public Nullable<int> Fat { get; set; }
        public Nullable<int> Sodium { get; set; }
        public Nullable<int> Fiber { get; set; }
        public Nullable<int> Carbo { get; set; }
        public Nullable<int> Sugar { get; set; }
        public Nullable<int> Potash { get; set; }
        public Nullable<int> Vitamins { get; set; }
        public Nullable<int> Shelf { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Cups { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
